#!/bin/bash

#scale Django app and test performance

DEPLOYMENT_NAME="django-app-deployment"
SERVICE_NAME="django-service"

echo "Scaling $DEPLOYMENT_NAME to 3 into 3 replicas"
kubectl scale deployment "$DEPLOYMENT_NAME" --replicas=3

echo "Waiting for pods to be ready"
kubectl rollout status deployment/"$DEPLOYMENT_NAME"

echo "List the  pods"
kubectl get pods -l app=django -o wide

#get the service url using minikube
SERVICE_URL=$(minikube service "$SERVICE_NAME" --url)
echo "Django messaging app available at - $SERVICE_URL"

echo "running load test using wrk - 10s duration, 5 thrds, 20 conns"
wrk -t5 -c20 -d10s "$SERVICE_URL"

echo "monitoring resource usage"
kubectl top pods
