#!/bin/bash

#automation script to switch from blu to green
# Author: Bashu-011

set -e  #incase of error exit

echo "Blue version deploying"
kubectl apply -f blue_deployment.yaml

echo "Green version deploying"
kubectl apply -f green_deployment.yaml

echo "applying service config"
kubectl apply -f kubeservice.yaml

echo "checking deployment status"
kubectl get deployments

echo "list of running pods"
kubectl get pods -l app=django

echo "logs for green deploymnt"
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath='{.items[0].metadata.name}')
kubectl logs $GREEN_POD --tail=20

echo "Blue - green setup complete"
echo "kubectl apply -f kubeservice.yaml"
